import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import "@rainbow-me/rainbowkit/styles.css";
import RainbowKitContext from "@/components/RainbowKit";
import Navbar from "@/components/Navbar";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  leaderboard,
}: Readonly<{
  children: React.ReactNode;
  leaderboard: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + "bg-agblack"}>
        <RainbowKitContext>
          <Navbar />
          {children}
          {leaderboard}
          <Toaster />
        </RainbowKitContext>
      </body>
    </html>
  );
}
